/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
*/

#include <iostream>
// using namespace std;

int main() {

    long int unsigned jumlah = 0;
    int x = 0, y = 0, z = 0;
    int unsigned fibonacci[1000] = {1,2};

    for(int i = 0; i < 100; i++){
        if(i > 1) {
            x = fibonacci[i-2] + fibonacci[i-1];
            fibonacci[i] = x;
        }
        if(fibonacci[i] > 4000000) {
            break;
        }
        std::cout << fibonacci[i] << " ";
        if(fibonacci[i] % 2 == 0) {
            jumlah += fibonacci[i];
        }
    }

    std::cout << "\n" << jumlah;

    return 0;
}